name: Bytecraft
version: 0.2
author: Sabersamus
main: info.bytecraft.Bytecraft
description: >
    A plugin I created for my server Bytecraft
database: true
loadafter: [Basic commands]
softdepend: [Bytes]
commands:
    home:
        description: manage your home
        permission: bytecraft.home
        usage: |
            /<command> - only works if you have your home saved
            /<command> save - saves or moves your home
    warp:
        description: warp to a location
        permission: bytecraft.warp
        usage: |
            /<command> [name]
    pos:
        description: shows you your position in the world
        usage: /<command>
    tpblock:
        description: manage your tpblock
        permission: bytecraft.tpblock
        usage: /<command> [on|off|status]
    tp:
        description: teleport to a player, doesn't work if the player has teleport block on(except for admins)
        permission: bytecraft.tp
        usage: /<command> [player]
permissions:
    bytecraft.admin:
        defualt: false
        children:
            bytecraft.home: true
            bytecraft.warp: true
            bytecraft.tpblock: true
            bytecraft.teleport.override: true
            bytecraft.teleport.silent: true
            bytecraft.teleport.admin: true
            bytecraft.god: true
            bytecraft.compass: true
            bytecraft.ban: true
            bytecraft.kick: true
            bytecraft.item: true
            bytecraft.give: true
            bytecraft.who: true
            bytecraft.tp: true
            bytecraft.inv: true
            bytecraft.teleport.admin: true
            bytecraft.mobspawn: true
            bytecraft.nuke: true
    bytecraft.guardian:
        default: false
        children:
            bytecraft.kick: true
            bytecraft.ban: true
            bytecraft.warp: true
            bytecraft.tp: true
            bytecraft.inv: true
    bytecraft.donor:
        default: false
        children:
            bytecraft.tpblock: true
            bytecraft.home: true
            bytecraft.member: true
    bytecraft.member:
        default: true
        children:
            bytecraft.warp: true
            bytecraft.tp: true